name: abel Push Docker
on:
  workflow_dispatch:
    inputs:
      registry:
        required: true
        type: choice
        options:
          - ali

run-name: Push to ${{ inputs.registry }}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: |
          echo "IMAGE_TAG=$(date +'%m%d')_${{ github.run_number }}" >> $GITHUB_ENV

      - name: Get env
        if: inputs.registry == 'ali'
        env:
          TZ: Asia/Shanghai
        run: |
          echo "REGISTRY=registry.cn-beijing.aliyuncs.com" >> $GITHUB_ENV
          echo "REPOSITORY=abelrepo/karakeep" >> $GITHUB_ENV

      - name: Login to docker
        if: inputs.registry == 'ali'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PWD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: SERVER_VERSION=nightly
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max